### ISSUE TITLE
Build error KotlinNullPointerException with gradle 6

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1044]
I'm researching it myself as well. Look like something related to the Realm database:

    Caused by: kotlin.KotlinNullPointerException
        at io.realm.processor.ModuleMetaData.getClassListFromModule(ModuleMetaData.kt:337)
        at io.realm.processor.ModuleMetaData.validateNamingPolicies(ModuleMetaData.kt:170)
        at io.realm.processor.ModuleMetaData.preProcess(ModuleMetaData.kt:113)
        at io.realm.processor.RealmProcessor.preProcessModules(RealmProcessor.kt:239)
        at io.realm.processor.RealmProcessor.process(RealmProcessor.kt:176)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.AggregatingProcessor.process(AggregatingProcessor.java:50)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.access$401(TimeTrackingProcessor.java:37)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:99)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:96)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.track(TimeTrackingProcessor.java:117)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.process(TimeTrackingProcessor.java:96)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 120 more

**Comment by colourful-land** [comment]
This issue can be reproduced on any version of JDK above 8. It won't worth the effort to solve it unless Android provides JDK 9+.

**Comment by colourful-land** [comment]
This has nothing to do with JDK version. The change of JDK version in my experiment simply triggered a gralde clean. Do a clean this problem will be gone.
