### ISSUE TITLE
Crash in Key Unlock/BiometricPrompt

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1616]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.hardware.fingerprint.FingerprintManager.getErrorString(int, int)' on a null object reference
       at android.hardware.biometrics.BiometricPrompt.lambda$sendError$0(BiometricPrompt.java:490)
       at android.hardware.biometrics.-$$Lambda$BiometricPrompt$HqBGXtBUWNc-v8NoHYsj2gLfaRw.run(:6)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

Not sure what is causing this. Could be that the prompt is missing a setup param?

The above is all the data about the crash I have. Since it's an issue with key usage I'm bumping the priority.

**Comment by ChintanRathod** [comment]
@JamesSmartCell Let me check the issue.

**Comment by JamesSmartCell** [comment]
Resolved by pulling the Biometric code out for now - mainly due to Samsung placing restrictions on how biometric unlock event works differently using fingerprint vs face-unlock.
