### ISSUE TITLE
uniswap cannot work

### ISSUE THREAD

**Issue by VliceZ** [AlphaWallet/alpha-wallet-android#1773]

**Comment by AW-STJ** [comment]
Hey @VliceZ, thanks for raising the issue. However, when we tested, Uniswap works fine on the latest version of Android in PlayStore. Can you describe the issue in more detail. Screenshots, errors, etc would help a lot.

Also please let us know the version of AlphaWallet and the device (manufacturer, model number) details that you are using. We are on Telegram for quick 1-1 support. https://t.me/AlphaWalletSupport

**Comment by VliceZ** [comment]
Thanks for your reply。I knew  why uniswap can't work anymore。The problem comes from the network，its works when i turned on VPN . but is cannot works when i shut down VPN，and i got this error on log console：
java.net.SocketTimeoutException: failed to connect to app.uniswap.org/157.240.12.36 (port 443) from /192.168.41.211 (port 49250) after 10000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
        at libcore.io.IoBridge.connect(IoBridge.java:130)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:357)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:201)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:183)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:616)
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.kt:57)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:266)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:180)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:238)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:111)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:79)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:163)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
        at okhttp3.RealCall.execute(RealCall.kt:67)
        at com.alphawallet.app.web3.JsInjectorClient.loadUrl(JsInjectorClient.java:81)
        at com.alphawallet.app.web3.Web3ViewClient.shouldInterceptRequest(Web3ViewClient.java:135)
        at com.alphawallet.app.web3.Web3View$WrapWebViewClient.shouldInterceptRequest(Web3View.java:353)
        at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:56)
        at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:9)
        at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:11)

My area is mainland China，and how can i resolve it？
Thank you very match。

**Comment by JamesSmartCell** [comment]
@VliceZ can you try an experiment for us? Can you open app.uinswap.org in a normal browser without VPN and see if it connects ok?

**Comment by VliceZ** [comment]
Yes i tried，its works fine  in a normal browser without VPN .

**Comment by VliceZ** [comment]
@AW-STJ @JamesSmartCell I need your help.Thank you very much.

**Comment by VliceZ** [comment]
I'm so sorry, it's all my fault. Uniswap cannot work in a normal browser without VPN ,This error has nothing to do with AlphaWallet.
