### ISSUE TITLE
Crash on personalSign

### ISSUE THREAD

**Issue by clehner** [AlphaWallet/alpha-wallet-android#2207]
Hi,
Thanks for making AlphaWallet!
I get a crash when confirming some signing requests.
Stack trace from log follows.
Here is the relevant line: https://github.com/AlphaWallet/alpha-wallet-android/blob/9ce511ee04d2522fd33c35e34092534e379c31de/app/src/main/java/com/alphawallet/app/viewmodel/DappBrowserViewModel.java#L139
```
11-02 18:06:46.236 16324 16324 D AndroidRuntime: Shutting down VM
11-02 18:06:46.238 16324 16324 E AndroidRuntime: FATAL EXCEPTION: main
11-02 18:06:46.238 16324 16324 E AndroidRuntime: Process: io.stormbird.wallet, PID: 16324
11-02 18:06:46.238 16324 16324 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int com.alphawallet.ethereum.NetworkInfo.chainId' on a null object reference
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.viewmodel.DappBrowserViewModel.signMessage(DappBrowserViewModel.java:139)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.ui.DappBrowserFragment.gotAuthorisationForSigning(DappBrowserFragment.java:1955)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.widget.ActionSheetDialog$1.gotAuthorisation(ActionSheetDialog.java:334)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.service.KeyService.checkAuthentication(KeyService.java:776)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.service.KeyService.getAuthenticationForSignature(KeyService.java:294)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.viewmodel.DappBrowserViewModel.getAuthorisation(DappBrowserViewModel.java:214)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.ui.DappBrowserFragment.getAuthorisation(DappBrowserFragment.java:1988)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.widget.ActionSheetDialog.signMessage(ActionSheetDialog.java:350)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.widget.ActionSheetDialog.handleClick(ActionSheetDialog.java:281)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.widget.FunctionButtonBar.handleStandardFunctionClick(FunctionButtonBar.java:253)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.widget.FunctionButtonBar.handleAction(FunctionButtonBar.java:226)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.alphawallet.app.widget.FunctionButtonBar.onClick(FunctionButtonBar.java:206)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at android.view.View.performClick(View.java:7259)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7236)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at android.view.View.access$3600(View.java:801)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:27892)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-02 18:06:46.238 16324 16324 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
11-02 18:06:46.247  1734 17090 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
11-02 18:06:46.247  1734 31862 W ActivityTaskManager:   Force finishing activity io.stormbird.wallet/com.alphawallet.app.ui.HomeActivity
11-02 18:06:46.275 16324 16324 I Process : Sending signal. PID: 16324 SIG: 9
```

**Comment by JamesSmartCell** [comment]
Thanks for reporting this! I have made a fix that will go into the next release
