### ISSUE TITLE
Support `awallet://wc?uri=wc%3Axxx` in addition to `wc:` making them do the same thing

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#3274]
If the format matches, extract the `uri` value and handle it the same way as we do for "wc:" currently.

Example (this example is with the v1 URL embedded, v2 works the same way), launching this in an Android browser:

`awallet://wc?uri=wc%3A5f577f99-2f54-40f7-9463-7ff640772090%401%3Fbridge%3Dhttps%253A%252F%252Fwalletconnect.depay.com%26key%3D1938aa2c9d4104c91cbc60e94631cf769c96ebad1ea2fc30e18ba09e39bc3c0b`

Should be equivalent to launching this:

`wc:5f577f99-2f54-40f7-9463-7ff640772090@1?bridge=https%3A%2F%2Fwalletconnect.depay.com&key=1938aa2c9d4104c91cbc60e94631cf769c96ebad1ea2fc30e18ba09e39bc3c0b`

For reference, this would be similar to how our deeplink (https://aw.app/openurl?url=<MagicLink>) is used to embed a MagicLink representing an SL pass.

**Comment by gvoltr** [comment]
Hello! Should this fix be available in v3.69 update of android app?
This is still not working for me with v3.69.


```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=awallet://wc?uri=wc:233b50592a7524543f2c3b69400890f37caff4e6737e7711cbff72b06140a8d6@2?relay-protocol=irn&symKey=e4cbd2383f955df7a9b09a35109f2395e6ba092c3b925a08c20d38e74731a4e0 flg=0x10000000 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2087)
  	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
  	at android.app.ContextImpl.startActivity(ContextImpl.java:1095)
  	at android.app.ContextImpl.startActivity(ContextImpl.java:1066)
  	at android.content.ContextWrapper.startActivity(ContextWrapper.java:421)

```
