### ISSUE TITLE
Activity not found for deeplink intent

### ISSUE THREAD

**Issue by gvoltr** [AlphaWallet/alpha-wallet-android#3318]
Hello! I'm trying to open wallet for conneciton with `awallet:` deeplink but it is not working.
I have Alpha Wallet v3.69 installed on my device.

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=awallet://wc?uri=wc:233b50592a7524543f2c3b69400890f37caff4e6737e7711cbff72b06140a8d6@2?relay-protocol=irn&symKey=e4cbd2383f955df7a9b09a35109f2395e6ba092c3b925a08c20d38e74731a4e0 flg=0x10000000 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2087)
  	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
  	at android.app.ContextImpl.startActivity(ContextImpl.java:1095)
  	at android.app.ContextImpl.startActivity(ContextImpl.java:1066)
  	at android.content.ContextWrapper.startActivity(ContextWrapper.java:421)
```

**Comment by JamesSmartCell** [comment]
Yes!! this is finally fixed

**Comment by gvoltr** [comment]
Do you mean this should be fixed in 3.69 or other release? I see the line about WC deeplinks in 3.69 changelog, but it still doesn't seem to work.

**Comment by JamesSmartCell** [comment]
No, its not in the live release yet, but has been fixed in the repo. It'll be in the next release

**Comment by JamesSmartCell** [comment]
It's live now.
