### ISSUE TITLE
Quit during launching (cannot enter main window)

### ISSUE THREAD

**Issue by bobjiang** [AlphaWallet/alpha-wallet-android#536]
Xiaomi MIX2
MIUI 10.2
Android 8.0.0

AlphaWallet version: Jan 29, 2019 from google play
Scenario: cannot enter main page, just quit after launching AlphaWallet.

**Comment by JamesSmartCell** [comment]
Hi Bob, snap I have the same phone but using a different version of MIUI. I've never seen this problem and it's not showing up as an issue so it's something else. I have a hunch it may be related to Firebase use in China.

Would you be able to install this attached debug build of AlphaWallet? 

https://drive.google.com/a/alphawallet.com/file/d/1lG_Ty6PTkVl4ENjhIThM4kN7yYE1tWNr/view?usp=sharing

To install, copy to your phone then browse using the Xiaomi file manager and click on it. You'll need to allow installation from other sources.

When it crashes it should display a white popup with '**view summary**' hotlink at the bottom. 

![crash](https://user-images.githubusercontent.com/12689544/52098426-01f42880-2623-11e9-8d32-07f57195e888.jpg)

Click on the view summary hotlink and take a screen shot of the exception you see and post it here please? We have added crashlytics but that isn't reporting anything in this case.

**Comment by bobjiang** [comment]
Hi James,

I downloaded apk file, but cannot install it.
During install, there is an error as following.

![image](https://user-images.githubusercontent.com/1224604/52129822-840c3d80-2673-11e9-9963-696a500c193e.png)

**Comment by cckole** [comment]
### App keeps crashing after launching

### Descriptions

After installing the app, I launched it and it opened, but crashed afterwards.

### Steps to reproduce

After installation

Launch the app. It will launch but crash immediately. 

### Expected behavior

When I launched the app, my expectation was to use the app further and not to be deprived of that by crashing.


### Reproducing the bug
https://youtu.be/GnUN1QixUgs


### Device used

Tekno spark k7

Android 7.0

### Logcat

```FATAL EXCEPTION: RxCachedThreadScheduler-6
06-12 08:15:51.953 22807 22898 E AndroidRuntime: Process: io.stormbird.wallet, PID: 22807
06-12 08:15:51.953 22807 22898 E AndroidRuntime: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoSuchMethodError: No interface method getTypeName()Ljava/lang/String; in class Ljava/lang/reflect/Type; or its super classes (declaration of 'java.lang.reflect.Type' appears in /system/framework/core-oj.jar)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No interface method getTypeName()Ljava/lang/String; in class Ljava/lang/reflect/Type; or its super classes (declaration of 'java.lang.reflect.Type' appears in /system/framework/core-oj.jar)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at org.web3j.abi.TypeReference.getClassType(TypeReference.java:64)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at org.web3j.abi.FunctionReturnDecoder.build(FunctionReturnDecoder.java:100)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at org.web3j.abi.FunctionReturnDecoder.decode(FunctionReturnDecoder.java:43)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.stormbird.wallet.repository.TokenRepository.getName(TokenRepository.java:870)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.stormbird.wallet.repository.TokenRepository.lambda$setupTokensFromLocal$30(TokenRepository.java:1167)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.stormbird.wallet.repository.-$$Lambda$TokenRepository$Dat7A2udQO7Zaiob3-J3ndnCfro.call(lambda)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.reactivex.Single.subscribe(Single.java:3603)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
06-12 08:15:51.953 22807 22898 E AndroidRuntime: 	... 6 more```

**Comment by James-Sangalli** [comment]
@bobjiang is this still an issue for you with the newer builds?

**Comment by bobjiang** [comment]
please close it, it works in some new versions, not sure which is the exact version.haha
