### ISSUE TITLE
Xiaomi mi9 crashes when focusing on getting the QR code

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#703]
I am not sure if @JamesSmartCell has Xiaomi so I am getting @hboon 's attention because he has an earlier Xiaomi.

The issue occurs when a user scans the QR code, this one. I tried to scan the phone with my HTC Exodus1 and it works for me.

![photo_2019-05-29_10-09-46](https://user-images.githubusercontent.com/548435/58520225-29868680-81fa-11e9-9d94-a0e770611d6b.jpg)

This might be the error he is having (the day of the event matches, 26th May, so it is likely the same crash error happened when that photo was taken). Also the error message matches the scenario: `Attempt to invoke virtual method 'void io.stormbird.wallet.entity.Token.setFocus(boolean)' on a null object reference`

    Fatal Exception: java.lang.RuntimeException: Unable to resume activity {io.stormbird.wallet/io.stormbird.wallet.ui.Erc20DetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.stormbird.wallet.entity.Token.setFocus(boolean)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3828)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3860)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6815)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

I attached the log here:

[io.stormbird.wallet_issue_crash_5CEBE42800E700012EB326AD3D2AC2DC_DNE_0_v2.gz](https://github.com/AlphaWallet/alpha-wallet-android/files/3230209/io.stormbird.wallet_issue_crash_5CEBE42800E700012EB326AD3D2AC2DC_DNE_0_v2.gz)

**Comment by yangwao** [comment]
Thanks for submitting it 🥰

**Comment by colourful-land** [comment]
@JamesSmartCell I heard you mentioning something like camera API, can you repeat it here so developers have a centralised location of information regarding any specific issue?

**Comment by James-Sangalli** [comment]
@colourful-land no xiaomi emulator in android studio, bring your phone in next week for testing

**Comment by JamesSmartCell** [comment]
Fixed by QR handling refactor.
