### ISSUE TITLE
Make TrustAddressGenerator work in Android

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#809]
Have a look at this branch:

[demonstrate-failure-including-xml-signature-code-in-android](https://github.com/AlphaWallet/alpha-wallet-android/tree/demonstrate-failure-including-xml-signature-code-in-android)

If you access settings -> help & faq you get this:

````
08-15 17:05:48.422  5922  5922 D AndroidRuntime: Shutting down VM
08-15 17:05:48.423  5922  5922 E AndroidRuntime: FATAL EXCEPTION: main
08-15 17:05:48.423  5922  5922 E AndroidRuntime: Process: io.stormbird.wallet, PID: 5922
08-15 17:05:48.423  5922  5922 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/crypto/dsig/XMLSignatureFactory;
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at io.stormbird.token.tools.XMLDSigVerifier.getValidXMLSignature(XMLDSigVerifier.java:120)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at io.stormbird.token.tools.TrustAddressGenerator.getXMLDSigSignedInfoDigest(TrustAddressGenerator.java:68)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at io.stormbird.token.tools.TrustAddressGenerator.getTrustAddress(TrustAddressGenerator.java:40)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at io.stormbird.wallet.ui.HelpActivity.lambdaDemo(HelpActivity.java:151)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at io.stormbird.wallet.ui.HelpActivity.onCreate(HelpActivity.java:81)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6986)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1232)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2857)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2979)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:180)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-15 17:05:48.423  5922  5922 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.crypto.dsig.XMLSignatureFactory" on path: DexPathList[[zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/base.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_dependencies_apk.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_resources_apk.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_0_apk.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_1_apk.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_2_apk.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_3_apk.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_4_apk.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_5_apk.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_6_apk.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_7_apk.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_8_apk.apk", zip file "/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/lib/arm64, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/base.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 	... 17 more
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/io.stormbird.wallet-PmfYBjoOcUA4xcBBd1uBZw==/split_lib_resources_apk.apk
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:100)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:74)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:46)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at android.app.LoadedApk.getResources(LoadedApk.java:936)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:2242)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6010)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at android.app.ActivityThread.-wrap1(Unknown Source:0)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
08-15 17:05:48.424  5922  5922 E AndroidRuntime: 		... 6 more
08-15 17:05:48.425  2852  3879 E ActivityManager: App crashed! Process: io.stormbird.wallet
````

**Comment by JamesSmartCell** [comment]
@colourful-land I believe we spoke at length about this issue - Android has had this class specifically removed which is why we needed to set up the signature verification server. There was a project attempting to add this back in but it was abandoned long ago possibly because it was unworkable.
