### ISSUE TITLE
NPE on compound function calls 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#813]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.stormbird.wallet, PID: 30612
    java.lang.NullPointerException: Attempt to invoke virtual method 'int io.stormbird.token.tools.TokenDefinition$As.ordinal()' on a null object reference
        at io.stormbird.wallet.ui.FunctionActivity.checkTokenScriptElement(FunctionActivity.java:335)
        at io.stormbird.wallet.ui.FunctionActivity.checkFunctionArgs(FunctionActivity.java:316)
        at io.stormbird.wallet.ui.FunctionActivity.handleConfirmClick(FunctionActivity.java:274)
        at io.stormbird.wallet.ui.FunctionActivity.onClick(FunctionActivity.java:257)
        at android.view.View.performClick(View.java:6891)
        at android.widget.TextView.performClick(TextView.java:12651)
        at android.view.View$PerformClick.run(View.java:26083)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by JamesSmartCell** [comment]
Unable to reproduce. Please specify how this happens.
